add check synk test version

diff --git a/.github/workflows/ensure-snyk-policy-version.yaml b/.github/workflows/ensure-snyk-policy-version.yaml
--- a/.github/workflows/ensure-snyk-policy-version.yaml
+++ b/.github/workflows/ensure-snyk-policy-version.yaml
@@ -19,6 +19,15 @@ jobs:
                 echo ".snyk file was missing or outdated."
                 echo $(cat .snyk)
               fi
+      - name: Check Snyk Test Version
+        run: |
+          echo "${{ secrets.SNYK_TEST_SHA }}" | sha256sum --check -
+          if [ $? -eq 0 ]; then
+                echo ".github/workflows/snyk-test.yaml is up-to-date."
+              else
+                echo ".github/workflows/snyk-test.yaml file was missing or outdated."
+                echo $(cat )
+              fi
   Trigger-Test:
     needs: Check-Policy
     name: Trigger Snyk test
