update snyk-test.yaml

diff --git a/.github/workflows/snyk-test.yaml b/.github/workflows/snyk-test.yaml
--- a/.github/workflows/snyk-test.yaml
+++ b/.github/workflows/snyk-test.yaml
@@ -1,30 +1,62 @@
-name: Snyk Security Scan
+name: Snyk SCA, Code, IaC and Container CLI monitor example
 
 on:
   workflow_dispatch:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+  # push:
+  #   branches: [ master ]
+  # pull_request:
+  #   branches: [ master ]
 
-jobs: 
+env:
+  SNYK_API: https://app.eu.snyk.io/api
   
-  snyk-full-scan:
+jobs:
+  build:
+    name: Test and build
     runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [16.x]
+
     steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for all vulnerabilities and exit
-        uses: snyk/actions/node@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}      
-        continue-on-error: true 
-  snyk-high-severity:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/node@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - uses: actions/checkout@v2
+
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
         with:
-          args: --severity-threshold=critical
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+
+      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+        run: |
+          npm install snyk -g
+          npm install snyk-filter -g
+          npm install snyk-to-html -g
+          snyk auth ${{ secrets.SNYK_TOKEN }}
+
+      - name: Setup the repo and install npm packages
+        run: |
+          npm install
+
+      - name: Snyk Open Source
+        run: |
+          snyk test --json | snyk-filter || true
+        # Run a snyk test and send the results into snyk-filter; failing on >2 high or >0 critical
+        # Remove || true to fail if the criteria is met
+
+      - name: Snyk Code
+        run: |
+          snyk code test || true
+        # Remove || true to fail if there are vulnerabilities
+
+      - name: Snyk Container
+        run: |
+          docker build . -t yourimage:tag
+          snyk container monitor yourimage:tag --file=Dockerfile
+        # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+
+      - name: Snyk IaC
+        run: |
+          snyk iac test || true
+        # Remove || true to fail if there are vulnerabilities
