update npm and snyk-test.yaml

diff --git a/.github/workflows/snyk-test.yaml b/.github/workflows/snyk-test.yaml
--- a/.github/workflows/snyk-test.yaml
+++ b/.github/workflows/snyk-test.yaml
@@ -38,16 +38,18 @@ jobs:
 
       - name: Setup the repo and install npm packages
         run: |
-          npm install
+          npm installsudo 
 
       - name: Snyk Open Source
         run: |
-          snyk test --json | snyk-filter
+          snyk test --json | snyk-filter || true
         # Run a snyk test and send the results into snyk-filter; failing on >2 high or >0 critical
+        # Remove || true to fail if the criteria is met
 
       - name: Snyk Code
         run: |
-          snyk code test
+          snyk code test || true
+        # Remove || true to fail if there are vulnerabilities
 
       - name: Snyk Container
         run: |
@@ -57,5 +59,5 @@ jobs:
 
       - name: Snyk IaC
         run: |
-          snyk iac test
-  
+          snyk iac test || true
+        # Remove || true to fail if there are vulnerabilities
